In [1]:
import numpy as np

In [4]:
np.__version__

'1.26.4'

In [5]:
arr = [1,2,3,4,5]

In [6]:
type(arr)

list

In [7]:
my_arr = np.array(arr)

In [8]:
type(my_arr)

numpy.ndarray

In [9]:
my_arr

array([1, 2, 3, 4, 5])

In [11]:
my_arr.shape

(5,)

In [19]:
arr_1 = [1,2,3,7,5]
arr_2 = [4,5,6,5,6]
arr_3 = [7,8,9,4,5]

new_arr = [arr_1,arr_2,arr_3]

In [20]:
new_arr = np.array(new_arr)

In [21]:
new_arr.shape

(3, 5)

In [22]:
new_arr.reshape(5,3)

array([[1, 2, 3],
       [7, 5, 4],
       [5, 6, 5],
       [6, 7, 8],
       [9, 4, 5]])

In [24]:
arr_5 = np.array([[1,2,3,4,5],[7,6,5,4,3] , [5,4,2,5,7]])

In [25]:
arr_5

array([[1, 2, 3, 4, 5],
       [7, 6, 5, 4, 3],
       [5, 4, 2, 5, 7]])

In [28]:
arr_5[0:2,0:3]

array([[1, 2, 3],
       [7, 6, 5]])

In [29]:
arr_5[1:3,3:5]

array([[4, 3],
       [5, 7]])

In [30]:
arr_5[1:,2:4]

array([[5, 4],
       [2, 5]])

In [34]:
arr_5[2:3,1:4]

array([[4, 2, 5]])

In [36]:
arr = np.arange(0,10,2)

In [37]:
arr

array([0, 2, 4, 6, 8])

In [38]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [40]:
arr1 = np.array([1,2,3,4,5,6])

In [41]:
arr1

array([1, 2, 3, 4, 5, 6])

In [42]:
arr1[3:] = 100

In [43]:
arr1

array([  1,   2,   3, 100, 100, 100])

In [44]:
arr2 = arr1
arr2[3:] = 500
arr2

array([  1,   2,   3, 500, 500, 500])

In [45]:
arr1

array([  1,   2,   3, 500, 500, 500])

In [46]:
arr3 = arr1.copy()

In [47]:
arr3[3:] = 600
arr3

array([  1,   2,   3, 600, 600, 600])

In [48]:
arr1

array([  1,   2,   3, 500, 500, 500])

In [49]:
np.ones(4)

array([1., 1., 1., 1.])

In [50]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [51]:
np.ones((3,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [52]:
np.random.randn(4,4)

array([[-0.13431736,  1.23824426,  2.69828026, -0.35191091],
       [ 0.43989977, -1.36990474, -0.99049423, -1.26463013],
       [-0.3675847 , -1.50583156,  1.17627917, -0.28399173],
       [ 0.84476866, -1.20403871, -0.37686031, -0.27372063]])

In [54]:
np.random.randint(0,100,8).reshape(4,3)

ValueError: cannot reshape array of size 8 into shape (4,3)